/**
 * Copyright 2015 Google Inc. All Rights Reserved.
 *
 * <p>Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * <p>http://www.apache.org/licenses/LICENSE-2.0
 *
 * <p>Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 */

/** Defines the keys for the well known labels used by the cloud debugger. */
package com.google.devtools.cdbg.debuglets.java;

/** Autogenerated high-level data structure for cloud debugger labels */
public final class Labels {
  /** Autogenerated labels for message Breakpoint */
  public static final class Breakpoint {

    public static final String REQUEST_LOG_ID = "requestlogid";

    private Breakpoint() {}
  }

  /** Autogenerated labels for message Debuggee */
  public static final class Debuggee {

    public static final String DOMAIN = "domain";
    public static final String PROJECT_ID = "projectid";
    public static final String MODULE = "module";
    public static final String VERSION = "version";
    public static final String MINOR_VERSION = "minorversion";

    private Debuggee() {}
  }

  private Labels() {}
}
